name: CI

on: [push]

jobs:
  test:
    name: test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        go_version: ['1.16', '1.17', '1.18', '1.19']

    steps:
      - name: set up go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: check out code into the go module directory
        uses: actions/checkout@v2

      - name: test
        run: go test -v -cover ./...
